apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
  labels:
   app: myapp
spec:
  replicas: 2
  selector:
   matchLabels:
    app: myapp
  template:
   metadata:
     labels:
      app: myapp
   spec:
     containers:
      - name: mysqlcontainer
        image: mysql
        ports:
         - containerPort: 3306
        env:
         - name: MYSQL_DATABASE
           valueFrom:
             configMapKeyRef:
               name: app-config
               key: MYSQL_DATABASE

         - name: MYSQL_ROOT_PASSWORD
           valueFrom:
             secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD        
