apiVersion: v1
kind: Pod
metadata:
  name:  pod-demo
spec:
  containers:
    - name: app
      image: nginx
      volumeMounts:
       - name: data
         mountPath: "/mnt/data"
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: pvc-demo
       
    
